### ISSUE TITLE
Add open source dep acknowledgements in settings

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/Freetime#106]

**Comment by Sherlouk** [comment]
I've used https://github.com/mono0926/LicensePlist in a few projects with good success!
With a small script can hook it into your Podfile as well to auto-update when ever you add/remove dependencies

**Comment by Sherlouk** [comment]
@rnystrom Do you want me to do a PR with the above library? Worth noting that it adds the acknowledgements to the Settings.Bundle (not your in-app settings page)

Which would you prefer?

**Comment by rnystrom** [comment]
@sherlouk let’s do it! If you want to put up a PR using this tool I’m down.
