### ISSUE TITLE
Add support for 1Password extension

### ISSUE THREAD

**Issue by kt-weyert** [rnystrom/Freetime#107]
When GitHub asks for your password you can't ask 1Password to fill in the pass as the share button is missing

**Comment by rnystrom** [comment]
@kt-weyert actually you can! It's just in the "share" option in the Safari view.

![img_4620](https://user-images.githubusercontent.com/739696/28047688-d728fa02-65b9-11e7-9fed-626ddd623221.PNG)

**Comment by weyert** [comment]
Let me have a look at it again. Clearly it was already 2am when I created this ticket. Maybe I didn't see the Share button it wasn't on the keyboard. Sorry!
