### ISSUE TITLE
Emoji doesn't animate sometimes

### ISSUE THREAD

**Issue by raulriera** [rnystrom/Freetime#108]
Rotating a few times stops or stars the floatting animation (sometimes it's stuck as well)

**Comment by rnystrom** [comment]
Thanks @raulriera! Fixed on `master`, will ship 1.0.1 with this fix.

**Comment by raulriera** [comment]
Seems to still happen in 1.0.1. It always shows at first launch. But background and foreground the app and the animation stops

**Comment by rnystrom** [comment]
Ah, found it. Fixing.

**Comment by raulriera** [comment]
Sorry to keep discussing this "non issue". But if you present a modal (settings screen for example) the animation stops and doesn't resume again until you exit and foreground the app. Probably something in viewWillDisappear when it shouldn't?

**Comment by rnystrom** [comment]
Will give it a look
