### ISSUE TITLE
Swipe notifications to dismiss

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/Freetime#11]
- Use SwipeCellKit
- Send notification POST request
- Optimistically dismiss
- Re-show if request fails

**Comment by BasThomas** [comment]
Just as an FYI: the SwipeCellKit behavior (aka the Mail.app behavior) is a public API in UIKit in iOS 11.

**Comment by rnystrom** [comment]
@basthomas on UICollectionView?

**Comment by rnystrom** [comment]
Looks like the new swipe actions are still table-only

**Comment by BasThomas** [comment]
Oh, right. 😩

**Comment by rnystrom** [comment]
Swipe view setup, just needs wiring
