### ISSUE TITLE
[Suugestion] Carthage support

### ISSUE THREAD

**Issue by unnamedd** [rnystrom/Freetime#110]
Is not a better option to use Carthage instead of CocoaPods ?

**Comment by rnystrom** [comment]
@unnamedd tbh b/c I've never used Carthage and I know how to use CocoaPods 😅 

I'm actually thinking about dropping CocoaPods altogether to improve build times. This app is <10k lines of Swift and takes _forever_ to compile already...

**Comment by rnystrom** [comment]
Gonna close since there's nothing to action yet

**Comment by unnamedd** [comment]
@rnystrom is interesting to you if I sent a PR changing from CocoaPods to Carthage?

**Comment by BasThomas** [comment]
What would the advantages of Carthage be in this case, @unnamedd?

**Comment by unnamedd** [comment]
@basthomas we will have these third libraries pre-compiled, then will add it into project, only the .frameworks. This will made the time to compile be improved and it will remove the needed to have the cocoapods installed to run the project after git clone

**Comment by BasThomas** [comment]
🤔, you shouldn't need CocoaPods anyway as the Pods directory is checked in.

**Comment by rnystrom** [comment]
@unnamedd sure! I'd take a look.
