### ISSUE TITLE
Signing out does not sign out

### ISSUE THREAD

**Issue by asos-dylanslewis** [rnystrom/Freetime#112]
Steps to reproduce:
- log in as a user
- do no change login state in Safari
- tap sign out in the app
- tap sign in on the welcome page

Expected behaviour:
- GitHub sign in page appears so I can log in as a different user

Actual behaviour:
- I'm logged in with the same user as I just signed out from

**Comment by rnystrom** [comment]
@asos-dylanslewis this is b/c you're still signed in via Safari. I switched to using the GitHub auth web flow which uses `SFSafariViewController` and shares cookies w/ Safari.app. If you want to change accounts, you can go into Safari, nav to github.com, and logout.

I had multiple account support before adding the web flow. Now that I know personal access tokens are a thing I might add it back in the future.

**Comment by BasThomas** [comment]
FWIW, in iOS 11 Safari VC cookies should not be shared with Safari, but are app-based. :)

**Comment by rnystrom** [comment]
Perfect!
