### ISSUE TITLE
RFC: Add multiple account support back (somehow)

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/Freetime#113]
I originally added multiple account support so I could swap between a main and test account, but I wonder how many people have other GitHub accounts they use often? (e.g. bots, "secret" accounts).

Some questions:

- Do you or people you know do this often?
- How do you manage (e.g. "private" browsing)

**Comment by rnystrom** [comment]
Inspired by #112

**Comment by dkhamsing** [comment]
Does not seem widely used. If I was gonna do this often, I would probably use different desktop browsers

**Comment by dkhamsing** [comment]
Should we close this issue, or #204 ?

**Comment by rnystrom** [comment]
oops good call
