### ISSUE TITLE
1.0.1 update blocked by Apple review

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/Freetime#117]
Some bug showing a white screen on sign in on iPad 👎

**Comment by macbellingrath** [comment]
@rnystrom  can you share any more info on device/os or steps to reproduce?

**Comment by rnystrom** [comment]
> Launch the app connected to the internet 
> Tap Sign in with GitHub
> App loads a blank white screen 

<img width="350" alt="ss1" src="https://user-images.githubusercontent.com/739696/28098580-1a4d0582-6685-11e7-8dc3-c6ca9ef5578f.png">

<img width="350" alt="ss2" src="https://user-images.githubusercontent.com/739696/28098579-1a4aaf9e-6685-11e7-8613-d727f10ada8a.png">

I've tried reproducing and can't. Submitting an appeal.

**Comment by dakeshi** [comment]
I got a similar rejects before. At that time, they mentioned IPv6 supports issues too. I solved this issue like you. Ask them to try launching the app again.

**Comment by rnystrom** [comment]
They fixed it, should be [available](https://itunes.apple.com/us/app/freetime-github-open-source-project-manager/id1252320249?ls=1&mt=8) soon
