### ISSUE TITLE
Merge events do not show up

### ISSUE THREAD

**Issue by BasThomas** [rnystrom/Freetime#122]
![img_2197](https://user-images.githubusercontent.com/4190298/28120104-601b45d2-6717-11e7-979d-419f94fa9605.JPG)
![img_2196](https://user-images.githubusercontent.com/4190298/28120105-603b26ea-6717-11e7-96f5-75ec0a89c1c8.JPG)

**Comment by rnystrom** [comment]
Limitation of the GitHub notifications API... 😢 

I'd consider using the [Events](https://developer.github.com/v3/activity/events/#list-public-events) API, but that shows stuff on your home page (so other user's activities). [example](https://gist.github.com/rnystrom/d17b09defe1ab3d251f51167b70539ef)

Gonna close unless you've got another idea?

**Comment by BasThomas** [comment]
Ugh. GitHub can and we can't. 😐

**Comment by rnystrom** [comment]
Ya pretty big limitation on the API. Also doesn't support releases, doesn't give you Issue/PR status in the endpoint, and more. Super limited...
