### ISSUE TITLE
Link issues when comma separated

### ISSUE THREAD

**Issue by viktorgardart** [rnystrom/Freetime#127]
See image.

![img_0132](https://user-images.githubusercontent.com/6084484/28144120-f5d0ec92-6769-11e7-9c6b-100b67194dc9.PNG)

**Comment by rnystrom** [comment]
The comma getting the link styling treatment? Ya weird. [The comment](https://github.com/rnystrom/Freetime/issues/83#issuecomment-314011529) is definitely correct...
