### ISSUE TITLE
Inconsistency with GitHub design for "closed via"

### ISSUE THREAD

**Issue by raulriera** [rnystrom/Freetime#129]
Inconsistency with the "closed via (commit)" on github. In the following image, it appears the issue was simply closed, when in fact it was closed due to a fix of a pull request. The github website presents that footer differently than Freetime app

## App
![img_0871](https://user-images.githubusercontent.com/24159/28150426-8b0dc4cc-6762-11e7-939f-1b4299f80063.PNG)

## GitHub
![img_0872](https://user-images.githubusercontent.com/24159/28150500-edba4f0a-6762-11e7-88be-14daba1ae4d3.PNG)

**Comment by rnystrom** [comment]
Good callout, I tried adding this recently via commit reference events. Let me see if its broken.

**Comment by rnystrom** [comment]
Aha, there's a `commit` field on [ClosedEvent](https://developer.github.com/v4/reference/object/closedevent/). Will update w/ that.
