### ISSUE TITLE
Show app version info in settings

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/Freetime#130]
Would be awesome to prefill that in bug reports, but not sure if that's possible.

**Comment by BasThomas** [comment]
Should be possible if we go native with creating issues: https://developer.github.com/v3/issues/#create-an-issue

**Comment by Sherlouk** [comment]
What about something like this?

https://github.com/rnystrom/Freetime/issues/new?title=I%20found%20a%20new%20bug&body=Version%201.0.0&labels=bug
