### ISSUE TITLE
Commenting: no indication of where I am commenting on

### ISSUE THREAD

**Issue by BasThomas** [rnystrom/Freetime#136]
Not sure how to tackle this / if this is really an issue, but it would be nice to know what I am commenting on - now, the VC's title is just "New Comment" and I have no idea on which issue I am commenting

**Comment by Sherlouk** [comment]
I'd honestly rather it didn't open a new VC at all, and was just an expandable textview at the bottom

**Comment by rnystrom** [comment]
Ya I'm with you, path of least resistance at the moment. Inline will require auto expanding UITextView. Plus I'll need a place to put:

- adding auto replies
- preview button
- UI real estate for autocomplete

Will give it some thought, not gonna prioritize it atm.

**Comment by rnystrom** [comment]
Alright, found a way to do this pretty easily, updating + sending new TF
