### ISSUE TITLE
Account name in settings appears as entered

### ISSUE THREAD

**Issue by BasThomas** [rnystrom/Freetime#15]
Logging in with "basthomas" displays "basthomas", logging in with "BASTHOMAS" displays "BASTHOMAS". Not sure if this is an issue?

**Comment by rnystrom** [comment]
I think that's ok. I might look to see if I can store the string that GH API gives me (might include caps formatting) but its pretty low pri.

**Comment by BasThomas** [comment]
Yeah, not that important. :)
