### ISSUE TITLE
Issue title doesn’t update but size does

### ISSUE THREAD

**Issue by Sherlouk** [rnystrom/Freetime#156]
Version: 1.2.0 (910)
Device: iPhone 6s Plus (iOS 11.0)

Was on the screen, issue title was updated, I did a pull-to-refresh and as the screenshot shows the size updated but the actual text did not!

Changing the segmented control did update the title eventually

![img_0187](https://user-images.githubusercontent.com/15193942/28248444-c7ffd172-6a3c-11e7-9c4f-b4d3d0642204.PNG)

**Comment by rnystrom** [comment]
Nice find!

**Comment by rnystrom** [comment]
done!
