### ISSUE TITLE
Settings page size not updated when multitasking

### ISSUE THREAD

**Issue by BasThomas** [rnystrom/Freetime#157]
Version: 1.2.0 (910)
Device: iPad Pro (iOS 10.3.2)
![img_0341](https://user-images.githubusercontent.com/4190298/28248602-97ab8678-6a47-11e7-8c9a-036976d49e0b.PNG)
![img_0342](https://user-images.githubusercontent.com/4190298/28248603-97ce41c2-6a47-11e7-8a1f-bf030330ea28.PNG)

**Comment by flovilmart** [comment]
Glad you love food and Rene Redzepi!
