### ISSUE TITLE
Can't load notifications after update

### ISSUE THREAD

**Issue by yusuftor** [rnystrom/Freetime#164]
Version: 1.2.0 (911)
Device: iPhone 6 Plus (iOS 10.3.2)

I just updated on the AppStore and opened the app and it comes up with "Cannot load notifications" on the main screen. If I pull to refresh it does nothing. I didn't have any notifications to start with anyway, but anyone else experiencing this issue or just me?

**Comment by rnystrom** [comment]
I think its a UI bug where if you have no notifications at all it shows this instead of saying something about being empty. It should show the empty UI instead. Tracking in #131
