### ISSUE TITLE
Generate Secrets in custom PLIST

### ISSUE THREAD

**Issue by heshamsalman** [rnystrom/Freetime#166]
Instead of doing [this](https://github.com/rnystrom/Freetime/blob/master/Classes/Other/Secrets.swift), might be a good idea to generate the secrets [similarly to this](https://github.com/heshamsalman/OctoViewer/blob/master/scripts/configs.rb) so that nobody can do anything malicious. 

Due to the nature of secret generation, @rnystrom would have to take this one on and instruct contributors to generate their own personal clientId/secret for their use.

**Comment by rnystrom** [comment]
I used to have this file checked in w/ some placeholders, then I moved it and all my secrets are out (oh no). 

Cool script! I like this.

**Comment by heshamsalman** [comment]
Could probably even leave the debug secret checked in, since it won't hit prod

**Comment by rnystrom** [comment]
Justed used [bfg](https://rtyley.github.io/bfg-repo-cleaner/) to strip secrets from git history and removed Secrets.swift from [git index](https://stackoverflow.com/questions/3319479/git-can-i-commit-a-file-and-ignore-the-content-changes). Should be g2g now.
