### ISSUE TITLE
Feature: open in Safari VC (instead of just Safari)

### ISSUE THREAD

**Issue by BasThomas** [rnystrom/Freetime#17]

**Comment by rnystrom** [comment]
This is for viewing issues on the web, right? Good idea, I'll update that.

**Comment by BasThomas** [comment]
Yes, that's the use case :)

**Comment by BasThomas** [comment]
Not sure if this is possible... played around with it for a bit (https://github.com/BasThomas/SafariVCActivity) but I can't seem to get it to work.

Doing [this](https://github.com/BasThomas/SafariVCActivity/blob/master/SafariVCActivity/SafariVCActivity.swift#L41-L44) kind of works, but is hacky and still has some issues with dismissing the SafariVC.

Doing [this](https://github.com/BasThomas/SafariVCActivity/blob/master/SafariVCActivity/SafariVCActivity.swift#L45-L48) is what I expected to "just work", but gives me a white screen with the view hierarchy as shown below.

<img width="1140" alt="screen shot 2017-06-27 at 22 49 47" src="https://user-images.githubusercontent.com/4190298/27609426-04bad532-5b8b-11e7-8c5b-ff9e4b6dbd81.png">

So, 🤷‍♂️

**Comment by rnystrom** [comment]
I can just change the menu to an alert control that has:

- Open in Safari
- Share...

I'll need that context menu for other stuff in the future:

- Close/re-open
- etc

**Comment by BasThomas** [comment]
Yeah, I wanted the "fancy" option. Of course that *would* work, should've it clearer that I was referring to using a `UIActivity`.
