### ISSUE TITLE
Ability to mark as read within the issue it self

### ISSUE THREAD

**Issue by viktorgardart** [rnystrom/Freetime#171]
Maybe add it in the ”three dot” menu?

Version: 1.2.0 (911)
Device: iPhone 7 Plus (iOS 11.0)

**Comment by BasThomas** [comment]
What's the use case? As I think this might get confusing with https://github.com/rnystrom/Freetime/issues/102 in place as well.

**Comment by viktorgardart** [comment]
@BasThomas didn't see #102, but when that's in place i don't see any use case for this. Closing! 👍
