### ISSUE TITLE
Issues not showing all events

### ISSUE THREAD

**Issue by BasThomas** [rnystrom/Freetime#173]
Noticed this in #134 and #139 which had a bunch of commits; not all messages there are shown (see screenshots), but neither are all the commits. Can the commits maybe be left out of the GraphQL query?

![img_1163](https://user-images.githubusercontent.com/4190298/28465617-a8017bfa-6e29-11e7-87e3-d33e03acd3fb.PNG)
![img_1164](https://user-images.githubusercontent.com/4190298/28465618-a803c810-6e29-11e7-873b-080d7b25f8b2.PNG)

**Comment by rnystrom** [comment]
This is from Issues missing paging support. Tracking in #29.

**Comment by Sherlouk** [comment]
Ah was bout to raise this again 😅 Good to know isn't just me, was super confused because it came up as unread but only contained one message which was 20 days old!

**Comment by rnystrom** [comment]
Aaaaaand fixed!

**Comment by Sherlouk** [comment]
ooft it works beautifully!
