### ISSUE TITLE
New Line Spacing

### ISSUE THREAD

**Issue by Sherlouk** [rnystrom/Freetime#189]
Not sure what the exact reasons are, but sometimes new paragraphs have massive gaps where others look "normal"

"Massive"
![image](https://user-images.githubusercontent.com/15193942/28692171-641ff39c-7317-11e7-8194-13d0c8f8c5fb.png)

"Normal"
![image](https://user-images.githubusercontent.com/15193942/28692189-7453784c-7317-11e7-8c58-46e3d6b6355f.png)

**Comment by rnystrom** [comment]
Need to take a look at the actual body response and see what the difference between the two could be. Noticed this myself.

**Comment by rnystrom** [comment]
Here's the body of that first issue:

```
Introduced FeedSelectionProviding to indicate when a selection has been made\r\nUpdated IssuesViewController and NotificationsViewController to conform to FeedSelectionProviding\r\nUpdated NotificationsViewController to show the placeholder when toggling the filter\r\nUpdated the SplitViewDelegate to depend on the current selection rather than a placeholder view
```

And body of the latter:

```
Ha, I figured there was, but maybe not 😞 \r\n\r\nThis would be lame, but maybe ⬜️ ?\r\n\r\nOtherwise we'll have to do text location finding, could be a huge PITA 😬 
```

I'll put both into an example issue and see how they are rendered to check if there's something different going on.

**Comment by rnystrom** [comment]
Ok, it's b/c there are 2x newlines between para's that don't have any whitespace in between. Weird! This is my bug.
