### ISSUE TITLE
Bug: 1Password integration empty

### ISSUE THREAD

**Issue by Sherlouk** [rnystrom/Freetime#19]
Pressed the button on login screen, share sheet opened but only had a "More" button which opened no apps.

Was no way to use 1Password from what I could tell?
(I have it installed, and use it)

Sometimes I dislike long passwords 😞
2FA support was nice though 😃 

iOS 11 beta 2, 6S+

**Comment by rnystrom** [comment]
@Sherlouk hmmmmmmmmm that's really weird... I'll install the TF build and take a look. Maybe some entitlements is messed up?

**Comment by Sherlouk** [comment]
Not sure how the 1Password app extension works so can't help with that one!

Screenshot though:
https://drive.google.com/file/d/0B8FbxFN4A3N6R3JVcjg5OVBNMWM/view?usp=sharing

**Comment by rnystrom** [comment]
Maybe an iOS 11 issue?

**Comment by Sherlouk** [comment]
Potentially, hence why I've been putting iOS 11 in my issues just in case :P

**Comment by Malecks** [comment]
I was able to login with 1Password on iOS 10 w/o issue

**Comment by Sherlouk** [comment]
Closing as 1PW has been removed from the project
