### ISSUE TITLE
Title for notification is hidden. 

### ISSUE THREAD

**Issue by RishabhTayal** [rnystrom/Freetime#195]
Here is a video showing the bug.

[SpringBoard.MP4.zip](https://github.com/rnystrom/Freetime/files/1183374/SpringBoard.MP4.zip)
Version 1.3.0 (1055)
Device: iPhone 7 Plus (iOS 11.0)

**Comment by Sherlouk** [comment]
Think this is a duplicate of #18, can you confirm?

**Comment by RishabhTayal** [comment]
Confirmed as duplicate.
