### ISSUE TITLE
All Comments Don't Load

### ISSUE THREAD

**Issue by ArtSabintsev** [rnystrom/Freetime#199]
Attempting to load comments in this [issue](https://github.com/ethereum/homebrew-ethereum/issues/116) only loads up to the following [comment](https://github.com/ethereum/homebrew-ethereum/issues/116#issuecomment-314320389).

The last two comments aren't loaded. Not sure if it's due to the _newness_ of those comments, or something else, like number of comments.

**Comment by BasThomas** [comment]
Think it's because of paging (#29), and should be fixed in the next beta. Right @rnystrom?

**Comment by rnystrom** [comment]
Yup! Submitted a build w/ this fix to the App Store as well as Testflight. Fixed soon 😄
