### ISSUE TITLE
Style Slack text view like rest of app

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/Freetime#206]
Should use `Styles`, match greys and blues

**Comment by BasThomas** [comment]
What do you expect here? The button [already has the blue color](https://github.com/rnystrom/Freetime/blob/master/Classes/Issues/IssuesViewController.swift#L83).

**Comment by BasThomas** [comment]
Also, that `isInverted` bool on the VC is so awefully named. :(

**Comment by rnystrom** [comment]
@BasThomas

- background
- border 
- placeholder

**Comment by rnystrom** [comment]
done
