### ISSUE TITLE
File change browsing on PRs

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/Freetime#209]
V1 can be read only (no commenting)

- show change summary in PR
- tap to go to file browser
- each file shows change summary
- tap to view changes

Nobody start on this yet. Going to be large and needs fleshed out more. Esp to prep for adding comments to files.

**Comment by Sherlouk** [comment]
Would definitely love to get syntax highlighting working with this as well

**Comment by rnystrom** [comment]
simple version done!
