### ISSUE TITLE
Bug: Notifications pane width doesn't update on rotate

### ISSUE THREAD

**Issue by Sherlouk** [rnystrom/Freetime#21]
iOS 11 beta 2, 6S+

From either notifications view or an issue view, rotating (which then does split screen) does not update the notifications pane width - this means that some of the text is cut off

If you pull to refresh or change the filter, this does update and fix it
The opposite it also happens if you have a thin version and go to portrait

**Comment by rnystrom** [comment]
Fixed in `master` 😉
