### ISSUE TITLE
Numbered list content is going on new line

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/Freetime#215]
https://github.com/Instagram/IGListKit/issues/869

Displays as:

```
1.

Bla bla bla

2.

Bla bla bla
```

**Comment by Sherlouk** [comment]
@rnystrom Not sure how precious you are about it but not sure if MMMarkdown is the best library 😅  Admittedly haven't looked at alternatives so not sure if it's just a section of iOS not well covered but seems to have quite a few issues and doesn't cover quite a few GitHub markdown components

**Comment by rnystrom** [comment]
@Sherlouk what components are missing? What other issues?

This bug is from my text rendering. MMMd is just for creating the AST, has nothing to do with rendering.

**Comment by Sherlouk** [comment]
Checklists are the obvious ones, but others like non explicit links/references #215 and other links - Possible to regex and iterate over it at the end but had wondered if something would do that for us

**Comment by rnystrom** [comment]
@Sherlouk are there any any libs that handle GH checklists? That's pretty non-trivial. I guess it'd work if using HTML, but 🚫 . 

The link stuff is all super-custom GitHub behavior, nothing to do w/ MD. Again I don't think another lib is going to help. Just going to have to roll our sleeves up and do it 😄
