### ISSUE TITLE
Bug: Relative time is incorrect

### ISSUE THREAD

**Issue by Sherlouk** [rnystrom/Freetime#22]
iOS 11 beta 2; 6S+

The relative time on actual GitHub says 5 hours ago, and the one in the app says 17 hours ago!

One of them must be wrong 🤔

**Comment by rnystrom** [comment]
@Sherlouk got a screenshot and link to where its wrong? What timezone is your phone and browser config'd as?

**Comment by Sherlouk** [comment]
https://drive.google.com/open?id=0B8FbxFN4A3N6VHh2bGx0dk9EV28
http://prntscr.com/fousi1
https://github.com/Instagram/IGListKit/issues/838

As you can see in the two images, the relative time is far apart - but the device times are just a few minutes as I took them!

My device time settings are 12hr automatically set for London, UK
