### ISSUE TITLE
Add network activity indicator 

### ISSUE THREAD

**Issue by BasThomas** [rnystrom/Freetime#221]
Version 1.4.0 (1136)
Device: iPhone 7 Plus (iOS 10.3.3)

**Comment by rnystrom** [comment]
What for?

**Comment by BasThomas** [comment]
More prominent feedback to the user when a network request is being made

**Comment by rnystrom** [comment]
Doesn't that happen already?

**Comment by rnystrom** [comment]
Tho I just sent this comment and didn't see one. I assumed all networking toggles the status.... 🤔

**Comment by BasThomas** [comment]
Don't think so 😬. Should be super easy to do, though: just this one line: https://github.com/Alamofire/AlamofireNetworkActivityIndicator
