### ISSUE TITLE
Large code blocks do not fully display

### ISSUE THREAD

**Issue by bigfish24** [rnystrom/Freetime#24]
The display of a large code block:
```
// Some code
//
//
//
//
// More code
//
//
//
//
// Even more code
//
//
//
```
Does not work properly.

**Comment by bigfish24** [comment]
![img_1241](https://user-images.githubusercontent.com/1036685/27615367-7816da82-5b5c-11e7-8d6a-201b7e3906d0.PNG)

**Comment by bigfish24** [comment]
Actual issue in example: https://github.com/realm/realm-cocoa/issues/5076

![img_1242](https://user-images.githubusercontent.com/1036685/27615391-a9d27770-5b5c-11e7-871f-f573aae95f30.PNG)

**Comment by rnystrom** [comment]
Ugh ya, noticed this last night. Fixed in master!
