### ISSUE TITLE
An issue is still visible on iPad after marking it read. 

### ISSUE THREAD

**Issue by shaps80** [rnystrom/Freetime#243]
On iPad the app only updates it’s detail view when a selection is made.

However marking an issue read, should ideally select the next issue below it (or above if no more below). 

When there are no more issues, it should display the empty view again. 

Version 1.5.0 (1330)
Device: iPad7,3 (iOS 11.0)

**Comment by rnystrom** [comment]
Hmm sort of a UI edge case. I actually disagree with this too. I'd rather not lose my spot. I view the detail pane almost like a separate tab. What do others think?

**Comment by BasThomas** [comment]
Nothing here would be ideal I suppose, so I'd not bother changing it.

**Comment by shaps80** [comment]
Maybe you're not understand my point. This is definitely not expected behaviour. 

Its like swiping in mail and selecting Archive. The item is removed from the list so I DEFINITELY wouldn't expect to still see the detail for it on the right.

Is that clearer? The detail view is showing me something I can no longer see in the list!

**Comment by rnystrom** [comment]
Ya, but the item isn't "deleted" persay, just marked read (and if you had "all" selected, it'd still be visible). I'm erring on no action since this could introduce other weird side effects.

**Comment by shaps80** [comment]
Well its up to you...

**Comment by Anviking** [comment]
I would probably expect the detail view to update too. What about animating the detail view along with the swipe or cell delete animation? Either to the next issue (prob not though), or just fade it away first. It would make the distinction clear(er) between "all" and "unread".

**Comment by BasThomas** [comment]
But then what would you expect to happen in `All`? Would it be persistent there, or should it fade away? Or should we even go to the next issue?

Think about this scenario:
1. Open unread issue in "unread"
2. Go to "all"
3. Mark issue as unread

What would you expect to happen?! I think leaving it as is would be the least confusing.

**Comment by shaps80** [comment]
@BasThomas simple!

The left hand side should always indicate what's being shown on the right. So in the scenario you suggested, switching back to the unread section would deselect any rows and show the empty view on the right – since the user has not made a new selection. Switching back to `All`, would do nothing in this case.

I don't want to add fire to the flame (apologies for creating this issue 😬) but IMHO (and pretty much all –decent– split-view apps appear to agree) selection is persistent on iPad, especially when dealing with a split-view.

Anyway the issue is closed and I totally accept that. I just felt it was inconsistent with most other iPad apps I use, and as a fairly heavy iPad user I tend to notice more than others. 😀

**Comment by shaps80** [comment]
@BasThomas One thing I should mention although I don't think it changes my point above.

Marking `Unread` has already been discussed as not happening since GitHub doesn't provide API for that.
