### ISSUE TITLE
iPad shows splitview detail pane when in 50/50 mode

### ISSUE THREAD

**Issue by BasThomas** [rnystrom/Freetime#27]
![img_0333](https://user-images.githubusercontent.com/4190298/27652014-7bd0f228-5c3a-11e7-9639-7b9729689de1.PNG)

**Comment by rnystrom** [comment]
Guess I need to buy an iPad pro, shucks.

Good find. I'm using the out-of-the-box `UISplitViewController` setup atm. I feel like even portrait mode could use the normal split VC (where primary is always visible).

**Comment by rnystrom** [comment]
@BasThomas you can still swipe on the left to reveal the notifications list, right?

**Comment by BasThomas** [comment]
Yep, that still works.

**Comment by BasThomas** [comment]
And portrait displays the detail fullscreen, even. So in portrait the whole screen wil be gray. 😱

**Comment by BasThomas** [comment]
Seems like you've fixed this. 😉
