### ISSUE TITLE
Soft read notifications when opening

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/Freetime#36]
Add note to a "soft read" status when opening (issue/commit/PR). Fades contents to 50% but DOESNT remove item (so you can go back). On reload the item is added to read list.

**Comment by rnystrom** [comment]
Not doing this, makes using the app more difficult. Must manually mark as read.

**Comment by BasThomas** [comment]
Maybe make this a setting? I would like this.

**Comment by rnystrom** [comment]
@BasThomas setting is a great idea
