### ISSUE TITLE
Issue title scrolls after opening on 7+

### ISSUE THREAD

**Issue by nanoxd** [rnystrom/Freetime#53]
When tapping an issue, after the segue there is a moment when the issue title is shown followed by a the view scrolling down to  Labels. The title is hidden unless you scroll the view down where you will see it until you’ve released your scroll. 

It might be an iOS 11 specific issue with the transition from `bottomLayoutGuide` to `safeAreaLayoutGuide`

Apologies for the lack of code blocks, can’t figure out where to find the back ticks on my phone. 

![img_1183](https://user-images.githubusercontent.com/1889575/27848926-cab56f28-60fd-11e7-8016-759de5b89117.PNG)

**Comment by BasThomas** [comment]
I'm not seeing this on iOS10. 

On backticks: you can long press `'` (bottom right).

**Comment by nanoxd** [comment]
@basthomas thanks!

**Comment by rnystrom** [comment]
Merging this into #18. Seems like an iOS 11 issue, gonna keep an eye on it, maybe file a radar if its easily reproducible. I'm still too scared to install the beta on my device 😨
