### ISSUE TITLE
Only showing a single notification

### ISSUE THREAD

**Issue by Malecks** [rnystrom/Freetime#54]
TestFlight Build running on  iOS 10.3.2

I'm only getting a single cell displaying in the read section with an 8 day old notification despite having 4 unread and several read notifications on the Github web interface.

At first I thought it was a private / public repository thing but the notification I get is from a private repository. Pull to refresh / relaunching / log-out has no effect.

**Comment by rnystrom** [comment]
Hmmm. @Malecks could you post a screenshot of the app and web notifications? You can blue out the titles if they are sensitive. I think there are certain types of notifications on web that the [GitHub notifications API](https://developer.github.com/v3/activity/notifications/) doesn't support.

**Comment by Malecks** [comment]
![image uploaded from ios 1](https://user-images.githubusercontent.com/15330064/27881666-925c4576-6197-11e7-92ab-326f7a9d58fe.jpg)
![image uploaded from ios](https://user-images.githubusercontent.com/15330064/27881667-926785f8-6197-11e7-94ef-b28dbd97995d.jpg)

Notifications that show in the app are indicated by the red arrows
![screen shot 2017-07-05 at 3 28 55 pm](https://user-images.githubusercontent.com/15330064/27881750-dc31c4fa-6197-11e7-94b5-915eafccbad9.png)

**Comment by rnystrom** [comment]
@Malecks is the greengage-ios a private repo?

**Comment by Malecks** [comment]
@rnystrom Yes it is! And that was my thought about why I'm not seeing notifications from there, however `greengage-mobile/whitelabel` is also private and I was able to see a notification from that repository in the app.

**Comment by rnystrom** [comment]
🤔 It looks like its an org permissions issue, gonna dig in this weekend and see what special stuff I need to do. Tracking in #60.
