### ISSUE TITLE
Not showing notifications from private repositories

### ISSUE THREAD

**Issue by narup** [rnystrom/Freetime#60]
I am only seeing notifications from the repositories I starred or commented. Nothing from my private repos. Also, not seeing anything from my own public repositories. 

This is my git url - https://github.com/narup

Thanks

**Comment by Sherlouk** [comment]
Given that it doesn't request permissions for anything on login, I assume it can only see public information - would be a nice feature though

**Comment by indyfromoz** [comment]
+1 to both @narup and @Sherlouk -- It will be awesome if we could see notifications from private repositories the user is member of and participating in PRs, issue discussions, etc. 

Perhaps a 2.0 feature?

**Comment by indyfromoz** [comment]
Checking Octobox (http://octobox.io), I found the Github client needs to request permissions to access the repositories of the organization(s) one is member of. 

![image](https://user-images.githubusercontent.com/315443/27886834-15c6effe-6221-11e7-801f-fbebfd315db2.png)

If the permission isn't available, I don't think if a Github client will be able to access notifications from private repositories.

**Comment by indyfromoz** [comment]
Another thought -- If Freetime requested user's list of repositories with the Github API upon successful authentication and displayed a list of repositories (including private repos), the app could then let the user select which repos they want to authorize thereby allowing notifications to be available.

**Comment by rnystrom** [comment]
Ya, I think I need to add the permissions requested via oauth

**Comment by narup** [comment]
👍

**Comment by rnystrom** [comment]
@narup @burnflare @Malecks @Sherlouk @indyfromoz I added `user` scope in the last build, but you'll need to re-auth (creates a new token w/ new scope). Mind logging out and back in and checking again?

I need to get a private org setup to test stuff out myself too. Combing the docs and not seeing anything special to do w/ orgs using Oauth. Might ping the octobox folks.

**Comment by Malecks** [comment]
@rnystrom no change for me after signing in / out, killing and restarting app etc. Running build 484.

**Comment by Sherlouk** [comment]
I didn't get prompted for extra permissions - nothing appears to be diff

**Comment by rnystrom** [comment]
Scopes don't prompt for anything, was just hoping the `user` would request the backend perms to work. But looks like private org repos need extra privileges. Will dig.

**Comment by rnystrom** [comment]
Ok I setup my own private repo to confirm, and reprod the issue. If this is a limitation of the `/notifications` endpoint, I'll either have to get creative, or (last resort) drop private repo support...

<img width="500" alt="screen shot 2017-07-08 at 11 13 03 am" src="https://user-images.githubusercontent.com/739696/27986575-bc259662-63ce-11e7-8d61-8d9b5f39fd0f.png">

![img_4603](https://user-images.githubusercontent.com/739696/27986577-c0958db0-63ce-11e7-81bf-cf938574894c.PNG)

**Comment by rnystrom** [comment]
Alright, got it figured out. Will be switching to web oauth flow, that's the only way to request/grant org access.

**Comment by rnystrom** [comment]
Solved org access w/ web flow: 

https://developer.github.com/apps/building-integrations/setting-up-and-registering-oauth-apps/about-authorization-options-for-oauth-apps/

My new private org notifications show up in my rest client, but not rendering in the app. Figuring that out.

**Comment by BasThomas** [comment]
Can we not have multiple accounts now?

**Comment by rnystrom** [comment]
@BasThomas nope, not w/ web auth. Sucks, but since GH doesn't really support it, I'm not going to hack around it either.

**Comment by BasThomas** [comment]
I am not seeing some notifs from a private repo, and they don't show up in the response either - regression?

**Comment by rnystrom** [comment]
Has the repo granted access to GitHawk?

**Comment by BasThomas** [comment]
Ah, that could be it 👍

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
Sorry for the false alarm 😬

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
I wonder if we can make it more clear somehow... probably some scanning on “new issue” before submitting would help.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
Maybe a simple FAQ? Could also mention this from the issue template 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
