### ISSUE TITLE
Half of issue is missing

### ISSUE THREAD

**Issue by Sherlouk** [rnystrom/Freetime#64]
Weird issue but heres the article I'm trying to view:
https://github.com/rnystrom/Freetime/issues/47

That issue was opened by Bas, and I commented in between Ryan's posts - yet in app I see this:

https://www.dropbox.com/s/96ftt2y5z35m1co/Photo%2006-07-2017%2C%2010%2055%2005%20am.png?dl=0

iOS 11 beta 2

**Comment by BasThomas** [comment]
FWIW, this is what I see on iOS 10. 
![img_1091](https://user-images.githubusercontent.com/4190298/27909579-a3139706-6251-11e7-809c-191c8ee252ad.PNG)

**Comment by Sherlouk** [comment]
Super bizarre!

**Comment by rnystrom** [comment]
Wtf

Ya it's all there for me on 10 too. Guess  e need an iOS 11 label!

**Comment by Sherlouk** [comment]
Sorry for all iOS 11 issues @rnystrom!

**Comment by Sherlouk** [comment]
Can I also mention (just noticed looking at the screenshot, the & symbol from your message is also gone @rnystrom)

**Comment by Sherlouk** [comment]
Get that this is an ios 11 bug but it really does just make the app unusable :(

https://www.dropbox.com/s/5mh38talgem09ic/Photo%2010-07-2017%2C%208%2050%2038%20am.png?dl=0

**Comment by Sherlouk** [comment]
@rnystrom Tried running it on iOS 11 simulator and couldn't reproduce - building directly onto my phone though has the issue?

Is there any tests or outputs I could send you that would help identify the cause of this?
Not sure if it's related to my time settings or what not

**Comment by Sherlouk** [comment]
Ooooh I've found out what's causing it, will try and find a fix!

**Comment by Sherlouk** [comment]
@rnystrom Okay so it's caused by 12/24hr setting on the device, assuming you have yours in 24hr maybe try putting it in 12hr and see if you have the same bizarre things happening to you?

Having played around it seems to break quite a lot:
- Which articles are read/unread
- Relative time
- What items are shown when you open an issue

The fix seems to be as simple as setting the locale on the date formatter to force it into a 24 hour format which is more consistent for the GitHub's APIs

```
// Line 15 - GitHubAPIDateFormatter
dateFormatter.locale = Locale(identifier: "en_US_POSIX")
```

**Comment by rnystrom** [comment]
wtf! That's crazy. Ok let's fix this, wanna send up a PR?

**Comment by Sherlouk** [comment]
Sure will be home in 10 mins
