### ISSUE TITLE
Mark issue as read from "all" makes cell blank

### ISSUE THREAD

**Issue by BasThomas** [rnystrom/Freetime#65]
Also, it seems like the cell / indexPath stays markable, which causes some weird issues too (screenshot 2)
![img_1092](https://user-images.githubusercontent.com/4190298/27909666-0cc269ca-6252-11e7-83ad-6af008b33f67.PNG)
![img_1093](https://user-images.githubusercontent.com/4190298/27909667-0cdd33a4-6252-11e7-9f7a-b1c8da7cba40.PNG)

**Comment by rnystrom** [comment]
Gross, just reproduced it myself. Big bug.
