### ISSUE TITLE
Layout not updated on screen change

### ISSUE THREAD

**Issue by BasThomas** [rnystrom/Freetime#7]
When changing orientation or the app's size in splitview on iPad, the layout isn't updated. Clicking something that causes some sort of refresh (focus on account in settings, switching state in notifications) fixes this. How can this be resolved best?

Impact: everything (except `GitHubLogin.storyboard`)

In a thread, tapping a comment fixes it only partially; the textview width is not updated.

<details>
  <summary>Screenshots</summary>

![simulator screen shot 25 jun 2017 16 36 23](https://user-images.githubusercontent.com/4190298/27517006-88eabaca-59c4-11e7-871b-7fb02deb12ac.png)

![simulator screen shot 25 jun 2017 16 36 28](https://user-images.githubusercontent.com/4190298/27517011-890a098e-59c4-11e7-8b2a-38f41c7696e3.png)

![simulator screen shot 25 jun 2017 16 36 31](https://user-images.githubusercontent.com/4190298/27517007-89062058-59c4-11e7-9626-a048dc02de37.png)

![simulator screen shot 25 jun 2017 16 36 37](https://user-images.githubusercontent.com/4190298/27517010-8907eb7c-59c4-11e7-8a54-30496b68901d.png)

![simulator screen shot 25 jun 2017 16 36 44](https://user-images.githubusercontent.com/4190298/27517008-8906f1f4-59c4-11e7-9ba4-c83e3571db8f.png)

![simulator screen shot 25 jun 2017 16 36 55](https://user-images.githubusercontent.com/4190298/27517009-8907933e-59c4-11e7-931f-bc8d9cc486d2.png)
</details>

**Comment by rnystrom** [comment]
Yup! Def a known issue. Going to have to figure out how to best clear text size and render caches when rotating. Think I have an idea...

**Comment by weyert** [comment]
Can't you listen to the orientation notification and clear the cache? Or would that cause a racing condition?

**Comment by rnystrom** [comment]
Fixed

@weyert I'm using sort-of-immutable models for this, but trying to dependency inject text+sizing models to the section controllers + cells that use them. Really trying to promote the "one way data flow" in this app w/out hacks. Also avoiding "global" caches and notification systems.
