### ISSUE TITLE
"Updated at" when refreshing

### ISSUE THREAD

**Issue by BasThomas** [rnystrom/Freetime#78]

**Comment by rnystrom** [comment]
🤔 like a timestamp of when you last refreshed? What for?

**Comment by Sherlouk** [comment]
Not a bad idea to be fair, especially on the "No New Notifications" page just a label which says
"Last Updated: 5 minutes ago"

There's no real feedback on a successful/invalid download so this would make it obvious

**Comment by rnystrom** [comment]
I'm gonna close this out, tbh I'd much rather have status messages if something is broken. Plus we've got "time since" timestamps which should communicate recency.
