### ISSUE TITLE
Incorrect layout when opening app in splitview after closing

### ISSUE THREAD

**Issue by BasThomas** [rnystrom/Freetime#86]
Steps to reproduce:

Open app
Make sure it is in splitview
Close app
Reopen app

![img_0337](https://user-images.githubusercontent.com/4190298/27996738-341cf190-64e9-11e7-8f93-9a76db3e447c.PNG)

(ref #7)

**Comment by rnystrom** [comment]
Noticed this today too! Weird, wonder if the iPad "changes" its layout when backgrounding/foregrounding or something...

**Comment by rnystrom** [comment]
Fixed!
