### ISSUE TITLE
Add haptic feedback to success / failure events

### ISSUE THREAD

**Issue by BasThomas** [rnystrom/Freetime#91]
Such as:

- [x] Succeeding to mark an issue as read (or is this already done by the SwipeCell?)
- [x] Failing to mark an issue as read
- [x] Succeeding to mark all issues as read
- [x] Failing to mark all issues as read
- [ ] ???

**Comment by rnystrom** [comment]
I think SwipeCellKit is already doing this (I can feel it). ❤️ the "mark all" feedback.
