### ISSUE TITLE
Show opened issues (as read) if no one has commented on them

### ISSUE THREAD

**Issue by BasThomas** [rnystrom/Freetime#94]
When you open an issue somewhere, it doesn't show up in the app until someone comments on it. On the GitHub website, there is the "Issues" page (https://github.com/issues) which does immediately show these issues. Is there an endpoint for that that can be used?

**Comment by BasThomas** [comment]
This would require additional request though, probably. :/

**Comment by rnystrom** [comment]
Longterm plan is to have a repos, search, and "saved" tab. Will def happen, just a few other things (like commenting) taking priority. Gonna close this and track a northstar for those tabs.
